stages:
  - build
  - test
  - deploy

singularity:
  stage: build
  needs: []  # run immediately
  tags:
    - docker
  image:
    name: quay.io/singularity/singularity:v3.2.1
    entrypoint: [""]
  script:
    - cp -r . /tmp/ink-id
    - singularity build inkid.sif singularity/inkid.def
  rules:
    # prevent builds just because branch is tagged
    - if: $CI_COMMIT_TAG
      when: never
    # only build on develop
    - if: '$CI_COMMIT_BRANCH == "develop"'

.test:
  stage: test
  needs: []
  before_script:
    - apt-get -y update
    # these packages are needed for Qt/GUI apps when running unit tests
    - apt-get -y install libgl1-mesa-glx
                         libopengl0 libegl1
                         libxkbcommon-x11-0
                         libdbus-1-3
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .
  script:
    - inkid-train-and-predict -h
    - python -m unittest
  tags:
    - docker

test:3.10:
  extends: .test
  image: python:3.10

pypi:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v.*$/'  # only run for tagged releases
  tags:
    - docker
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pip build setuptools wheel twine
  script:
    - python -m build --sdist
    - python -m twine upload dist/*

test:pages:
  stage: test
  tags:
    - docker
  image: python:3.10
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .
    - pip install --upgrade sphinx sphinx-rtd-theme
  script:
    - sphinx-build -b html docs/source public
  only:
    - branches
  except:
    - master

pages:
  stage: deploy
  tags:
    - docker
  image: python:3.10
  before_script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .
    - pip install --upgrade sphinx sphinx-rtd-theme
  script:
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
      - public
  only:
    - develop
